### ISSUE TITLE
Check that the required environment variables are defined at startup

### ISSUE THREAD

**Issue by volovikariel** [GryPr/Vireo#30]

**Comment by volovikariel** [comment]
@GryPr What should we do if a environment variable is not defined. Should we print out which ones aren't defined and raise a custom exception?

**Comment by GryPr** [comment]
> @GryPr What should we do if a environment variable is not defined. Should we print out which ones aren't defined and raise a custom exception?

Yep, depending on the variable we can raise a custom exception that'll fatal exit (bot token, db user and db user password as you put in the PR).

I think your PR is pretty much what I was thinking too.

**Comment by volovikariel** [comment]
#31
